kind: Service
apiVersion: v1
metadata:
  name: msa-apireg-service
spec:
  selector:
    app: msa-apireg
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apireg-service
  labels:
    app: apireg-service
    visualize: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apireg-service
  template:
    metadata:
      labels:
        app: apireg-service
        version: "1.0.0-RELEASE"     
    spec:
      containers:
      - name: msa-apireg-service
        image: docker.gsp.sicc.co.kr/apireg:1.0.0-RELEASE
        ports:
        - name: http
          containerPort: 8761
